### ISSUE TITLE
Enforcing Monotonicity?

### ISSUE THREAD

**Issue by 13bzhang** [GP-AI/cdf2pdf#4]
This is a suggestion. Maybe Allan or Toby have different opinions. For the CDF, do we want to enforce monotonicity in the responses? It would sort of weird if you select 30% probability at year 2020 and then 20% probability at year 2030. 

We had this problem in the 2016 AI Expert Survey for a few of the responses. It could be that respondents were filling out responses without thinking too much about it. Anyways, that problem caused us some headache so I'm inclined to enforce monotonicity in the responses.

**Comment by clareification** [comment]
Resolved
